name = "SimpleMatch"
uuid = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
